parameters:
  gitHubConnection: ''
  preRelease: false
  kspVersion: ''
  projectName: ''
  projectVersion: ''

jobs:
- job: Release
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'build_archive'
      downloadPath: '$(System.ArtifactsDirectory)'

    - task: GitVersion@5
      inputs:
        runtime: 'full'

  - task: ArchiveFiles@2
    displayName: 'Archive $(System.ArtifactsDirectory)/build_archive'
    inputs:
      rootFolderOrFile: '$(System.ArtifactsDirectory)/build_archive'
      includeRootFolder: false
      archiveFile: '${{ parameters.projectName }}-ksp${{ parameters.kspVersion }}-${{ parameters.projectVersion }}.zip'

  - task: GitHubRelease@1
    displayName: 'GitHub release (create)'
    inputs:
      gitHubConnection: ${{ parameters.gitHubConnection }}
      repositoryName: $(Build.Repository.Name)
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      title: 'ksp${{ parameters.kspVersion }}-${{ parameters.projectVersion }}'
      releaseNotesFilePath: '$(System.ArtifactsDirectory)/build_archive/CHANGELOG.md'
      assets: '${{ parameters.projectName }}-ksp${{ parameters.kspVersion }}-${{ parameters.projectVersion }}.zip'
      isPreRelease: ${{ parameters.preRelease }}
      addChangeLog: false
